apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydp
  namespace: prod
  annotations:
    kubernetes.io/change-cause: "this is my first version pods"
spec:
   minReadySeconds: 5
   replicas: 4
   selector:
    matchLabels:
      app: myapp
   strategy:
      type: {{ .Valueshelm.strategy.dptype}} 
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
   template:
     metadata:
       name: mydp
       labels:
         app: myapp
     spec:
      containers:
        name: mycondp
        image: {{ .Valueshelm.myimage}}
        ports:
         - containerPort: 80
    


